export const FETCH_PIZZA_LIST = 'FETCH_PIZZA_LIST';
export const PIZZA_CHANGE_FORM_VALUE = 'PIZZA_CHANGE_FORM_VALUE';
export const PIZZA_CREATE_NEW = 'PIZZA_CREATE_NEW';
export const PIZZA_VALIDATION = 'PIZZA_VALIDATION';
export const PIZZA_SNACKBAR = 'PIZZA_SNACKBAR';
export const PIZZA_UPDATE = 'PIZZA_UPDATE';
export const PIZZA_COPY = 'PIZZA_COPY';
export const PIZZA_PAG_PROPERTIES = 'PIZZA_PAG_PROPERTIES';
