export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const USER_CHANGE_FORM_VALUE = 'USER_CHANGE_FORM_VALUE';
export const USER_CREATE_NEW = 'USER_CREATE_NEW';
export const USER_UPDATE_FIELD = 'USER_UPDATE_FIELD';
export const USER_DELETE = 'USER_DELETE';
