export const FETCH_INGREDIENT_LIST = 'FETCH_INGREDIENT_LIST';
export const INGREDIENT_CHANGE_FORM_VALUE = 'INGREDIENT_CHANGE_FORM_VALUE';
export const INGREDIENT_CREATE_NEW = 'INGREDIENT_CREATE_NEW';
