export const FETCH_INGREDIENT_LIST = 'FETCH_INGREDIENT_LIST';
export const INGREDIENT_CHANGE_FORM_VALUE = 'INGREDIENT_CHANGE_FORM_VALUE';
export const INGREDIENT_CREATE_NEW = 'INGREDIENT_CREATE_NEW';
export const INGREDIENT_VALIDATION = 'INGREDIENT_VALIDATION';
export const INGREDIENT_SNACKBAR = 'INGREDIENT_SNACKBAR';
export const INGREDIENT_COPY = 'INGREDIENT_COPY';
export const INGREDIENT_UPDATE = 'INGREDIENT_UPDATE';
