export const FETCH_MENU = 'FETCH_MENU';
export const TOGGLE_CUSTOM_PIZZA_DIALOG = 'TOGGLE_CUSTOM_PIZZA_DIALOG';
export const CUSTOM_PIZZA_EDIT = 'CUSTOM_PIZZA_EDIT';
export const CUSTOM_PIZZA_VALIDATION = 'CUSTOM_PIZZA_VALIDATION';
