export const FETCH_SHOPPING_CART = 'FETCH_SHOPPING_CART';
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const REMOVE_FROM_SHOPPING_CART = 'REMOVE_FROM_SHOPPING_CART';
export const SHOPPING_CART_SNACKBAR = 'SHOPPING_CART_SNACKBAR';
export const EMPTY_SHOPPING_CART = 'EMPTY_SHOPPING_CART';
export const SHOPPING_CART_DIALOG = 'SHOPPING_CART_DIALOG';
export const SEND_ORDER = 'SEND_ORDER';

export const CART_CUSTOMER_EDIT = 'CART_CUSTOMER_EDIT';
export const CART_CUSTOMER_ERROR_EDIT = 'CART_CUSTOMER_ERROR_EDIT';

export const CHANGE_PIZZA_INGREDIENTS = 'CHANGE_PIZZA_INGREDIENTS';
export const TOGGLE_EDIT_INGREDIENTS_DIALOG = 'TOGGLE_EDIT_INGREDIENTS_DIALOG';
export const SELECT_PIZZA_TO_EDIT_INGREDIENTS = 'SELECT_PIZZA_TO_EDIT_INGREDIENTS';
