export const FETCH_SHOPPING_CART = 'FETCH_SHOPPING_CART';
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const REMOVE_FROM_SHOPPING_CART = 'REMOVE_FROM_SHOPPING_CART';
export const SHOPPING_CART_SNACKBAR = 'SHOPPING_CART_SNACKBAR';
export const EMPTY_SHOPPING_CART = 'EMPTY_SHOPPING_CART';
export const SHOPPING_CART_DIALOG = 'SHOPPING_CART_DIALOG';
