export const FETCH_ORDERS = 'FETCH_ORDERS';
export const CHECKBOX_STATUS_CHANGE = 'CHECKBOX_STATUS_CHANGE';
export const CHANGE_ORDER_STATUSES = 'CHANGE_ORDER_STATUSES';
export const CANCEL_ORDER_DIALOG = 'CANCEL_ORDER_DIALOG';
export const PICK_ORDER_CANCEL = 'PICK_ORDER_CANCEL';
export const ORDER_DETAIL = 'ORDER_DETAIL';
